" Modeline and Notes [
" vim: set foldmarker=[,] foldlevel=0 foldmethod=marker ts=4 sw=4 sts=4 nowrap spell:
" ]

" Environment [
	set nocompatible				" must be first line

	" Pathogen Support [
		runtime! bundle/pathogen/autoload/pathogen.vim
		silent! call pathogen#infect()
		silent! call pathogen#helptags()
	" ]

	filetype plugin indent on		" detect filetypes
	syntax on						" syntax highlighting
	set dir=~/.swp					" don't litter project with ~ files
	set hidden						" allow switching buffers without saving
	set history=50					" keep 50 lines of command line history
	set mouse=a						" enable the mouse
	set switchbuf+=usetab			" switch to open buffer first, rather than
									"	duplicating file in current buffer
	set viminfo+='100,f1			" history between sessions

	" restores normal vim keybindings for macvim
	if has("gui_macvim")
		let macvim_skip_cmd_opt_movement = 1
	endif

	" Jump to last cursor position [
		" Don't do it when the position is invalid or when inside an event
		" handler (happens when dropping a file on gvim).
		autocmd BufReadPost *
				\ if line("'\"") > 0 && line("'\"") <= line("$") |
				\   exe "normal! g`\"" |
				\ endif
	" ]
" ]

" Vim Settings [
	source $VIMRUNTIME/macros/matchit.vim	" enable % matching
	let &showbreak=nr2char(8618).'  ' " show arrow at beginning of wrapped lines
	set autoindent					" always set autoindenting on
	set backspace=indent,eol,start	" backspace over everything
	set colorcolumn=+1				" show textwidth limit
	set completeopt=menuone,longest	" insert completion
	set foldcolumn=1				" click to fold
	set gdefault					" global subst. by default; use '/g' to revert
	set hlsearch					" highlight search
	set ignorecase					" ingnore case in searches
	set incsearch					" do incremental searching
	set linebreak                   " wrap lines sanely
	set matchtime=1                 " showmatch is annoying
	set nostartofline				" keeps cursor in same spot when scrolling
	set number						" line number, c.f. 'relativenumber'
	set ruler						" show the cursor position all the time
	set scrolloff=3					" keep cursor from edges
	set showcmd						" display incomplete commands
	set showmatch					" highlight matching braces
	set smartcase					" don't ignore case with uppercase in pattern
	set spelllang=en_us				" made in the USA
	set tags+=tags;/				" search for tags in higher directories
	set title						" better titles in terminals
	set whichwrap+=<,>,[,]			" changing lines with arrow keys
	set wildignore=*.o,*.a,*.so,*.swp,*.aux,*.pdf " hide from completion
	set wildmenu					" tab completion on commands
	set wildmode=longest:full,list:full	" bash compatible behavior
	set winaltkeys=no				" turns off Alt for menu navigation
	set winminheight=0				" collapse windows to just the statusline
" ]

" Vim UI [
	" Colors [
		colorscheme molokai
		set bg=dark

		" Molokai customizations [
			highlight Comment		gui=italic guifg=#909090
			highlight Macro			gui=none
			highlight StatusLine	guifg=#b84c00
			highlight Search		guifg=#ffffff guibg=#b84c00
			highlight SpellBad		cterm=undercurl ctermbg=233
		" ]

		if has("gui_running")
			set guioptions-=T
			set columns=85			" 80 + 1 (foldcolumn) + 4 (number)
			" see .gvimrc
		else
			set t_Co=256			" number of colors in terminal
			set bg=dark				" must come after colorscheme
		endif

		" Highlight trailing whitespace
		highlight Trailing ctermbg=LightRed guibg=LightRed
		au BufEnter * match Trailing /\s\+$/
		au InsertEnter * match Trailing /\s\+\%#\@<!$/
		au InsertLeave * match Trailing /\s\+$/
	" ]
	" Statusline [
		set laststatus=2						" always show statusline
		set statusline=%f						" filename
		set statusline+=\ %w%h%m%r				" flags
		set statusline+=\ %Y                    " filetype
		set statusline+=\ [%<%{getcwd()}]\      " current dir
		set statusline+=%=%-11.(%l,%c%V%)\ %p%% " file nav info
	" ]
" ]

" Maps And Commands [

	" Reset leader to something easier to type
	let mapleader = ","

	" more logical behavior of Y
	nnoremap Y y$

	" alternate escape
	" inoremap jj <ESC>

	" make the . command return to the point where the command started
	noremap . .`[
	"]

	" Toggle word capitalization
	inoremap <C-U> <ESC>g~iwgi

	" Push line down, up in command mode (can delete lines)
	nnoremap + maO<esc>`a
	nnoremap _ makdd`a

	" Move line(s) up or down (swaps with adjacent lines)
	nnoremap <M-=> mz:m+<CR>`z
	nnoremap <M--> mz:m-2<CR>`z
	vnoremap <M-=> :m'>+<CR>`<my`>mzgv`yo`z
	vnoremap <M--> :m'<-2<CR>`>my`<mzgv`yo`z

	" put current word on commandline
	cmap <F2> <C-R><C-W>

	" Write buffer through sudo
	cnoreabbrev w!! w !sudo tee % >/dev/null

	" ` is more useful but less accessible than '
	nnoremap ' `
	nnoremap ` '

	" unhighlight after search
	nmap <silent> <leader><space> :silent :nohlsearch<CR>

	" move by screen line, not file line
	nnoremap j gj
	nnoremap k gk

	" Filename, line, and tag completion [[
	inoremap <C-F> <C-X><C-F>
	inoremap <C-L> <C-X><C-L>
	inoremap <C-]> <C-X><C-]>

	" Command to change to the directory of the current window (LCD) and all
	" windows (GCD)
	command! CD lcd %:p:h
	command! LCD lcd %:p:h
	command! GCD cd %:p:h

	" visual shifting (does not exit Visual mode)
	vnoremap < <gv
	vnoremap > >gv

    " Maps to create expanded open brackets. [
		" Depends on UltiSnips plugin. The <C-V> allow me to enter the <C-M>
		" (the carriage return) literally.
		" inoremap <silent> (<cr> ()<C-R>=UltiSnips_Anon('(<C-V><C-M><tab>${1:${VISUAL}}<C-V><C-M>)', '()', 'exp_paren',   'i')<cr>
		" inoremap <silent> {<cr> {}<C-R>=UltiSnips_Anon('{<C-V><C-M><tab>${1:${VISUAL}}<C-V><C-M>}', '{}', 'exp_stache',  'i')<cr>
		" inoremap <silent> [<cr> []<C-R>=UltiSnips_Anon('[<C-V><C-M><tab>${1:${VISUAL}}<C-V><C-M>]', '[]', 'exp_bracket', 'i')<cr>
		"]
	"]

	" DiffOrig [
		"Command to see the difference between the current buffer and the file
		"it was loaded from, thus the changes you made.
		command! DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
				\ | wincmd p | diffthis
	"]

	" Function to trim trailing white spaces [
		function! <SID>TrimTrailingSpaces()
			let l = line(".")
			let c = col(".")
			%s/\s\+$//e
			call cursor(l, c)
		endfunction
		command! TrimTrailingSpaces :call <SID>TrimTrailingSpaces()
	" ]
" ]

" Plugins [
	" LaTeX [
		let g:tex_flavor='latex'			" Sets .tex to be LaTeX file type
	" ]

	" NERDComments [
		let NERDCommentWholeLinesInVMode=1
		let NERDSpaceDelims=1
        let NERDCompactSexyComs=1
        let NERDCustomDelimiters = {
            \ 'snippets' : { 'left': '#' }
        \ }
	" ]

	" NERDTree [
		let NERDTreeIgnore=['\.o$']
		let NERDTreeChDirMode=2			" change dir when changing root
		let NERDTreeShowBookmarks=1
	" ]

	" SuperTab [
		let g:SuperTabDefaultCompletionType = 'context'
		let g:SuperTabMappingForward = '<C-Space>'
		let g:SuperTabMappingBackward = '<S-C-Space>'
		let g:SuperTabCrMapping = 0
		let g:SuperTabLongestEnhanced = 1
		let g:SuperTabLongestHighlight = 1
	" ]

	" UltiSnips [
		let g:ulti_user = "Sam Britt"
        let g:ulti_email = "samuelbritt@gmail.com"
		let g:UltiSnipsEditSplit = "horizontal"
        " see also mappings above
	" ]

	" Taglist [
		map <F2> :TlistToggle<CR>
	" ]

	" TaskList [
		map <leader>l <Plug>TaskList
	" ]
" ]
