# Alias definitions

# Platform and machine specific aliases
if [ `uname` = "Linux" ] ; then
	# alias open='gnome-open'
	alias open='kde-open'
	export PDFVIEWER='kde-open'
	alias lss='ls --ignore=*.o --ignore=*.pyc'
	alias lsd='ls --group-directories-first' #works on ubuntu
	alias matcl='matlab -nosplash -nodesktop'
	alias mvim="gvim"
	alias mvimdiff="gvimdiff"
	alias mendeley="mendeleydesktop &"
	export EPD=/opt/epd/bin

elif [ `uname` = "Darwin" ] ; then
	alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
	export PDFVIEWER='open'
	alias gvim="mvim"
	alias gvimdiff="mvim -d"
	alias mvimdiff="mvim -d"
	alias ls="ls -p"
	alias lss="ls *.cpp *.h"
	alias tree="find . -print | sed -e 's;[^/]*/;|_;g;s;_|; |;g'"
	alias showhidden="defaults write com.apple.finder AppleShowAllFiles TRUE; killall Finder"
	alias hidehidden="defaults write com.apple.finder AppleShowAllFiles FALSE; killall Finder"
	export EPD=/Library/Frameworks/Python.framework/Versions/Current/bin
fi

# Common alias definitions.
alias ll='ls -hl'
alias la='ls -A'
alias lal='ll -A'

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias gitroot='cd $(git root)'
alias hgroot='cd $(hg root)'
alias dirs="dirs -v"
alias pu='pushd'
alias po='popd'
alias ph='pushd ~'

alias grep="grep --color=auto"
alias today='date +%F'
alias now='date +%F-%H%M'
alias bc='bc -l'
alias scr='screen -DR'
alias df='df -H'
alias du='du -h'
alias pacman='pacman-color'
alias diff='colordiff -u'
alias make='colormake'
alias pylab='ipython --pylab'
alias epython='$EPD/python'
alias eipython='$EPD/ipython'
alias epylab='eipython -pylab'
alias tarz='tar czf'
alias untarz='tar xzf'
alias cleanlatex='rm -f *.aux *.bbl *.blg *.fdb_latexmk *.fls *.log *.out'
alias subl='/cygdrive/C/Program\ Files/Sublime\ Text\ 3/sublime_text.exe'

# bad typing with git
alias gi=git

# bad typing with hg
alias gh=hg
function h {
	case "$1" in
		gst | gts)
			command hg st "${@:2}"
			;;
		gsum)
			command hg sum "${@:2}"
			;;
		gic | gci)
			command hg ci "${@:2}"
			;;
		gfe)
			command hg fe "${@:2}"
			;;
		gdiff | gidff)
			command hg diff "${@:2}"
			;;
		glate | galte)
			command hg late "${@:2}"
			;;
		*)
			# just pass command through
			command "$0" "$@"
			;;
	esac
}


# recursive mkdir and cd if successful
function mkcd {
	mkdir -p "$@" && builtin cd "$@"
}

# cd and ls
function cl {
	cd "$@" && ls
}

# create a pretty-printed man page
function manp {
	file=/tmp/man_"$@".pdf
	man -t "$@" | ps2pdf - $file && open $file
}

# vim: set ft=sh nospell:
