# Alias definitions

# Platform and machine specific aliases
if [ `uname` = "Linux" ] ; then
	alias open='gnome-open'
	alias lss='ls --ignore=*.o --ignore=*.pyc'
	alias lsd='ls --group-directories-first' #works on ubuntu
	alias abaqus='XLIB_SKIP_ARGB_VISUALS=1 abaqus'
	alias cae='abaqus cae&'
	alias matcl='matlab -nosplash -nodesktop'
	alias mvim="gvim"
	alias mvimdiff="gvimdiff"
	export EPD=/opt/epd/bin

	# Edit file in new terminal window
	function tvim {
		gnome-terminal -x vim $@ &
	}
elif [ `uname` = "Darwin" ] ; then
	alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
	alias gvim="mvim"
	alias gvimdiff="mvim -d"
	alias mvimdiff="mvim -d"
	alias ls="ls -p"
	alias lss="ls *.cpp *.h"
	alias tree="find . -print | sed -e 's;[^/]*/;|_;g;s;_|; |;g'"
	alias showhidden="defaults write com.apple.finder AppleShowAllFiles TRUE; killall Finder"
	alias hidehidden="defaults write com.apple.finder AppleShowAllFiles FALSE; killall Finder"
	export EPD=/Library/Frameworks/Python.framework/Versions/Current/bin
fi

if [ $HOSTNAME = "hydrogen.site" ]
then
	alias open='kde-open'
fi


# Common alias definitions.
alias ll='ls -hl'
alias la='ls -A'
alias lal='ll -A'

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias dirs="dirs -v"
alias root='cd `hg root`'
alias pu='pushd'
alias po='popd'
alias ph='pushd ~'

alias grep="grep --color=auto"
alias today='date +%F'
alias now='date +%F-%H%M'
alias bc='bc -l'
alias scr='screen -DR'
alias df='df -H'
alias du='du -h'
alias diff='colordiff -u'
alias make='colormake'
alias pylab='$EPD/ipython -pylab'
alias epython='$EPD/python'
alias eipython='$EPD/ipython'

# bad typing with hg
alias gh=hg
function h {
	case "$1" in
		gst)
			command hg st "${@:2}"
			;;
		gts)
			command hg st "${@:2}"
			;;
		gsum)
			command hg sum "${@:2}"
			;;
		gic)
			command hg ci "${@:2}"
			;;
		gci)
			command hg ci "${@:2}"
			;;
		gfe)
			command hg fe "${@:2}"
			;;
		gdiff)
			command hg diff "${@:2}"
			;;
		gidff)
			command hg diff "${@:2}"
			;;
		glate)
			command hg late "${@:2}"
			;;
		galte)
			command hg late "${@:2}"
			;;
		*)
			# just pass command through
			command "$0" "$@"
			;;
	esac
}


# recursive mkdir and cd if successful
function mkcd {
	mkdir -p "$@" && builtin cd "$@"
}

# cd and ls
function cl {
	cd "$@" && ls
}

if [ ${HOSTNAME:0:9} = "moleculos" ] ; then
	unalias diff
fi

# vim: set ft=sh nospell:
