#!/bin/bash
#
# Common bash settings

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# prompt:
PS1='\n\u@\h:\w\n\$ '

# Aliases in .bash_aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# LaTeX
export BIBINPUTS=.:$HOME/texmf/bibtex/bib

# paths
export PYTHONPATH=$HOME/bin:$PYTHONPATH
export PATH=$HOME/bin:$PATH

#Vim keybindings
set -o vi

