#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Platform-specific settings
if [ `uname` = "Linux" ] ; then
	#color support of ls
	if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
		eval "`dircolors -b`"
		alias ls='ls --color=auto -Bpv'
		alias dir='dir --color=auto -pv'
	fi

elif [ `uname` = "Darwin" ] ; then
	# color support
	export CLICOLOR=1
	export LSCOLORS=ExGxCxDxCxegedabagacad
	export VIMRUNTIME='/Applications/MacVim.app/Contents/Resources/vim/runtime'
	export PATH=/usr/local/bin:$PATH # (mostly for exuberent ctags)
	# PATH DISPLAY variables for use with MacPorts
	export PATH=/opt/local/bin:/opt/local/sbin:$PATH

	# Setting PATH for EPD
	# The orginal version is saved in .bash_profile.pysave
	export PATH="/Library/Frameworks/Python.framework/Versions/Current/bin:${PATH}"
	export MKL_NUM_THREADS=1

	# Setting PATH for MacTeX
	export PATH=$PATH:/usr/texbin
fi

# Machine-specific settings
if [ `uname -n` = "titanium" ] ; then
	# Abaqus:
	export SIMULIADIR=/opt/simulia
	export ABAQUSDIR=$SIMULIADIR/abaqus
	export PATH=$PATH:$ABAQUSDIR/Commands
	# Intel Compilers:
	source /opt/intel/Compiler/11.1/072/bin/ifortvars.sh intel64
	# Matlab:
	export MATLABPATH=$HOME/bin:$HOME/lib/matlab:$MATLABPATH
	# EPD
	export PATH=/opt/epd/epd7.0/bin:$PATH
elif [ ${HOSTNAME} = "hydrogen" ] || [ ${HOSTNAME} = "hydrogen.site" ] ; then
	export PATH=/opt/bin:$PATH
	export PATH=/usr/sbin:$PATH
	# EPD
	export PATH=$PATH:/opt/epd/bin
elif [ `uname -n` = "silicon" ] ; then
		export PATH=$PATH:/opt/epd/bin
		export PATH=/opt/eclipse:$PATH
elif [ ${HOSTNAME} = "aluminum-vert" ] ; then
	# Intel Compilers:
	source /opt/intel/Compiler/11.1/073/bin/ifortvars.sh ia32
elif [ ${HOSTNAME:0:9} = "moleculos" ] ; then
	# Abaqus:
	export ABAQUSDIR=/opt/abaqus
	export PATH=$PATH:$ABAQUSDIR/Commands

	# Matlab
	export PATH=$PATH:/opt/matlab

	# Maui Scheduler
	export MAUIHOMEDIR=/usr/local/maui
	export PATH=$PATH:$MAUIHOMEDIR/bin
	export PATH=$PATH:$MAUIHOMEDIR/sbin

	# PATH
	export PATH=$PATH:/sbin
	export PATH=$PATH:/usr/sbin
	export PATH=$PATH:/usr/local/sbin
elif [ ${HOSTNAME} = "titan" ] ; then
	# Abaqus:
	export ABAQUSDIR=/usr/local/abaqus
	export PATH=$PATH:$ABAQUSDIR/Commands

	# PATH
	export PATH=$PATH:/sbin
	export PATH=$PATH:/usr/sbin
fi


# Common Settings

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export HISTCONTROL=ignoreboth # ignore dupes and lines starting with spaces
export HISTSIZE=5000 # number of stored commands

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Aliases found in .bash_aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

## xmodmap key bindings
# if [ -f ~/.xmodmap ]; then
#         xmodmap ~/.xmodmap
# fi

# prompt
PS1='\n\u@\h:\w\n\$ '

# LaTeX
export BIBINPUTS=.:$HOME/texmf/bibtex/bib

# paths
# export PYTHONPATH=$PYTHONPATH:$HOME/bin
# export PYTHONPATH=$PYTHONPATH:$HOME/lib/python
# export PATH=$PATH:$HOME/bin
export PATH=$HOME/.local/bin:$PATH
# this ^^^ may be all we need---installing python packages with
#	setup.py install --user
# installs scripts to ~/.local/bin, and modulus to ~/.local/lib/python*/site-packages
# and the PYTHONPATH is taken care of automagically

#Vim keybindings
set -o vi
