#!/bin/bash

# Platform-specific settings
if [ `uname` = "Linux" ] ; then
	#color support of ls
	if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
		eval "`dircolors -b`"
		alias ls='ls --color=auto -Bp'
		alias dir='dir --color=auto -p'
	fi
elif [ `uname` = "Darwin" ] ; then
	# color support
	export CLICOLOR=1
	export LSCOLORS=ExGxCxDxCxegedabagacad
	export VIMRUNTIME='/Applications/MacVim.app/Contents/Resources/vim/runtime'
	# PATH DISPLAY variables for use with MacPorts 
	export PATH=/opt/local/bin:/opt/local/sbin:$PATH
fi

# Machine-specific settings
if [ `uname -n` = "titanium" ] ; then
	# Abaqus:
	export SIMULIADIR=/opt/simulia
	export ABAQUSDIR=$SIMULIADIR/abaqus
	export PATH=$PATH:$ABAQUSDIR/Commands
	# Intel Compilers:
	source /opt/intel/Compiler/11.1/072/bin/ifortvars.sh intel64
	# Matlab:
	export MATLABPATH=$HOME/bin:$HOME/lib/matlab:$MATLABPATH
elif [ ${HOSTNAME:0:9} = "moleculos" ] ; then
	# Abaqus:
	export ABAQUSDIR=/opt/abaqus
	export PATH=$PATH:$ABAQUSDIR/Commands

	# Matlab
	export PATH=$PATH:/opt/matlab

	# Maui Scheduler
	export MAUIHOMEDIR=/usr/local/maui
	export PATH=$PATH:$MAUIHOMEDIR/bin
	export PATH=$PATH:$MAUIHOMEDIR/sbin

	# PATH
	export PATH=$PATH:/sbin
	export PATH=$PATH:/usr/sbin
	export PATH=$PATH:/usr/local/sbin
elif [ ${HOSTNAME} = "titan" ] ; then
	# Abaqus:
	export ABAQUSDIR=/usr/local/abaqus
	export PATH=$PATH:$ABAQUSDIR/Commands

	# PATH
	export PATH=$PATH:/sbin
	export PATH=$PATH:/usr/sbin
fi


# Common Settings

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export HISTCONTROL=ignoreboth # ignore dupes and lines starting with spaces
export HISTSIZE=5000 # number of stored commands

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Aliases found in .bash_aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# prompt
PS1='\n\u@\h:\w\n\$ '

# LaTeX
export BIBINPUTS=.:$HOME/texmf/bibtex/bib

# paths
export PYTHONPATH=$PYTHONPATH:$HOME/bin
export PYTHONPATH=$PYTHONPATH:$HOME/lib/python
export PATH=$HOME/bin:$PATH

#Vim keybindings
set -o vi
